//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_Site_Group_Project.Components.Layout;

public partial class NavMenu
{
    int role = PageHiding.role;
    public static int Admin = (int)Role.Admin;
    public static int Employee = (int)Role.Employee;
    public static int Customer = (int)Role.Customer;
}